export const SurvivorBingo = [
    "Jury member is needlessly bitchy.",
    "Jury member is incredibly bitter about losing.",
    "That's all I needed to hear.",
    "Why do you deserve it more than them?",
    "1 Jury member is the voice of reason.",
    'Jury member: Clap, rub, "well"',
    "Jury member professes love.",
    "Member of the final 3 cries",
    "Jeff has a dramatic live show entrance.",
    "Final 3 member says they proved something to themself/didn't think they could do this.",
    "Final 3 member has an unrecognizable glow up.",
    "Unanimous vote.",
    "Only one person gets zero votes.",
    "Reunion: Jeff gets an idea for the next season.",
    "Reunion: Jeff awkwardly reveals couple.",
    "Reunion: Someone has a dumb haircut.",
    "Reunion: Jeff theoretically polls jury.",
    "Reunion: Someone's opinion 100% flips from final tribal.",
    "Reunion: Reussel looks pissed.",
    "Reunion: Jeff asks about someone's dating/sex life.",
    "Reunion: Someone is still a petty bitch.",
    'Jury member: "Well, well, well".',
    'Jury member: "First of all, congratulations on getting this far".',
    "Jury doesn't have a question for someone because they were so bad.",
    "Jury member: tells someone to be mean.",
    "Jury member: really rude to 2 people and really nice to 1."
];